### ISSUE TITLE
Some icons not accessible when using an app with many menus and/or narrow screen

### ISSUE THREAD

**Issue by gingerbeardman** [Mortennn/Dozer#111]
# Problem
1. Use an app with many menus, eg. Safari
2. Have a load of menu icons and/or use a narrow screen
3. Try to access the left most icon

# Expected
- should be able to access all icons

# Actual
- cannot access some icons

![Screen shot 2020-04-19 at 18 46 17](https://user-images.githubusercontent.com/49612/79695356-4b538680-826e-11ea-8d28-7b3272549022.png)

# Workaround
- sometimes you can switch to an app with fewer menus, eg. Finder

![Screen shot 2020-04-19 at 18 46 28](https://user-images.githubusercontent.com/49612/79695358-4ee70d80-826e-11ea-8d7a-e7754d5387d5.png)

- but even then some are unavailable

![Screen shot 2020-04-19 at 18 46 41](https://user-images.githubusercontent.com/49612/79695361-51e1fe00-826e-11ea-942a-d8640d28f3c0.png)

- an app with one menu will let me get at them all

![Screen shot 2020-04-19 at 18 49 35](https://user-images.githubusercontent.com/49612/79695442-cb79ec00-826e-11ea-9900-864b30622fef.png)

# Extras 
- here's an app with one small menu item https://github.com/Mortennn/Dozer/issues/111#issuecomment-653469183
- here's a Dozer app with dock icon and one small menu item https://github.com/Mortennn/Dozer/issues/111#issuecomment-653750135

# Suggestion

- Make Dozer show it's own menu in certain circumstances

**Comment by decadent** [comment]
Some apps, like Bartender, create a dock icon on-the-fly for this condition, when the user requests all the status icons to be shown. This puts the app in the menu, and it has no menus other than the app name.

Bartender also seems to somehow detect dynamically when the current app has too many or too wide menus.

**Comment by pr0jectile** [comment]
Also experiencing this issue on a Macbook Pro 15-inch, 2018 model. Is this being looked into?

**Comment by gingerbeardman** [comment]
Any thoughts @Mortennn @aonez ?

**Comment by aonez** [comment]
@gingerbeardman the suggestion of @decadent seems doable and may work.

> Bartender also seems to somehow detect dynamically when the current app has too many or too wide menus.

I don't have a clue how to do this...

**Comment by decadent** [comment]
My guess is that, for detection, Bartender just accesses the menus through the standard API (the same that you can use in AppleScript) and then calculates the width in pixels by rendering the text on an internal invisible canvas, adding some fixed values for the padding between menu items.

Properly, with this approach the app should process changes in the focused app's menus—dunno is that's impossible or problematic. Parameters of the menu font should be taken from the system settings.

The values may be easily cached until menus of an app change.

**Comment by gingerbeardman** [comment]
My workaround for this is a little app I created called Menu.app which shows a minimal menu when you run it, allowing you to hopefully see all your Dozer icons.

[Menu.zip](https://github.com/Mortennn/Dozer/files/4869118/Menu.zip)

**Comment by gingerbeardman** [comment]
One more thought, is that if Dozer is built to have a dock icon `LSUIElement=NO` then switching to Dozer could show a single menu item and achieve this in a more self-contained way.

So here's a signed Dozer 4.2.0 that acts like that
[Dozer.app.420.zip](https://github.com/Mortennn/Dozer/files/4869627/Dozer.app.420.zip)

**Comment by gingerbeardman** [comment]
It does seem possible to do it programmatically, see here: https://stackoverflow.com/questions/620841/how-to-hide-the-dock-icon

Will try when I have some time

**Comment by gingerbeardman** [comment]
OK, I've done it and it works well! 

I also needed to activate the app after showing the icon.

Now to tie it to a preference (toggle) or heuristic (icons are more than half of screen?)

**Comment by decadent** [comment]
IMO for starters it would be alright if Dozer displayed the dock icon when showing the extra status icons, without other conditions. Showing the extra icons isn't supposed to be a frequent operation, I think—so it's alright even if a bit of delay is introduced to the dock icon.

Regarding the heuristics, measuring just the icons isn't enough since different people use different screens, and on my Macbook some apps' menus pretty much encroach on the status icons even when only a few are shown. Properly, width of the menu should be taken into account, but that can be done later. Or, if displaying the dock icon together with the extra status icons works well, then smart heuristics may be omitted altogether.

**Comment by decadent** [comment]
BTW, if more info is desired in regard to creating the dock icon, [Hammerspoon's code](https://github.com/Hammerspoon/hammerspoon) can be consulted: it can show or hide the icon by preference, and also [has a Lua api to do that](https://www.hammerspoon.org/docs/hs.dockicon.html).

**Comment by gingerbeardman** [comment]
Currently I am recording the leftmost icon in use (remove or left dot) and if the position of that is more than half a screen, it shows the icon. On my narrow Portrait display, that makes sense for the apps I've been using since.

My logic is a little wrong as Dozer menu still appears at times.

I think you might be right that I am overcomplicating things, I should just show it all the time perhaps with a preference to turn this on/off.

**Comment by gingerbeardman** [comment]
OK, I've made it so it shows it every time. No preference right now.

Feel free to try what I have so far: [Dozer.app.zip](https://github.com/Mortennn/Dozer/files/4871839/Dozer.app.zip)

**Comment by decadent** [comment]
@gingerbeardman It says, “the app is damaged and can't be opened”.

Could you please publish the code in a branch in your fork, for example? No offense but—that would also help with the nagging itch I get when when my open-source software isn't quite that open.

**Comment by gingerbeardman** [comment]
Sure! I'll do that today on my fork

**Comment by gingerbeardman** [comment]
Here we go! https://github.com/gingerbeardman/Dozer/tree/IconAndMenu

**Comment by gingerbeardman** [comment]
My fork/branch now has preferences added, and some small UI tweaks.

I'm thinking about adding a new tab to the app with simple usage instructions.

**Comment by gingerbeardman** [comment]
How are you finding using it @decadent ?

**Comment by decadent** [comment]
I wasn't keeping my Xcode setup well-oiled, and building the project is likely to be a bit of a major endeavor on my machine and with my luck—hopefully I'll get around to it later on the weekend. But if the PR happens to be merged before that, I'll probably be pretty happy.

Gotta say though, the option title sounds somewhat convoluted. I'd go with just: “When showing icons, free up the menu bar”, and in the subtitle: “Dozer will display a dock icon so it can replace the running application's menu”. Seeing icons in the menu bar is the main thing, and the dock icon is just a necessary side-effect.

**Comment by gingerbeardman** [comment]
Yes, good point. I'll charge the text when revising the PR

**Comment by gingerbeardman** [comment]
What about this:

> **Use full screen width when showing menu bar icons**
> Temporarily replaces Application menu and shows Dozer dock icon.

![Screen shot 2020-07-05 at 12 46 26](https://user-images.githubusercontent.com/49612/86531935-8ce2ed80-bebd-11ea-9d1f-f42b16d3ccd5.png)

**Comment by gingerbeardman** [comment]
Tightening up the finer points of how this works, there were a couple of holes in the option-click hide/show.

I would like the app to give up its focus when all icons are hidden again. Trying to figure that out. If anybody knows or has any hints please mention them. Thanks!

**Comment by aonez** [comment]
Did not tried it but maybe:


https://developer.apple.com/documentation/appkit/nsapplication/1428428-deactivate

**Comment by aonez** [comment]
This will do:


https://developer.apple.com/documentation/appkit/nsapplication/1428733-hide

```
 [[NSApplication sharedApplication] hide:self];

```

**Comment by gingerbeardman** [comment]
Yes, I thought so too.

But it seems the Dozer icon that has been clicked has some sort of focus and it is not hidden/deactivated.

It's an annoying extra click to return to previous app that I'd like to get rid of.

```
NSApp.deactivate()
NSApp.hide(self)
```

**Comment by gingerbeardman** [comment]
`NSApp.deactivate()` is definitely not correct, because if this mode is active and the Dozer icon is clicked _whilst the preference window is shown_ then the preference window no longer allows interactions due to it being deactivated.

`NSApp.hide(self)` does not have any visible effect.

**Comment by decadent** [comment]
I vaguely remember that I was solving pretty much the same problem by forcefully focusing the previously active application. However can't recall where I was doing that: possibly that was some sort of background notification app, which therefore could get the active app before activating itself. So, I'm not sure if Mac's API provides the previously-active app.

But! Since Dozer is doing sorta the same thing by creating its own active quasi-window, I think it might also be able to retrieve the focused application before creating the dock icon. And then pass the focus back to it when it's done.

There's a detail that the user might (and will) pull the rug from under Dozer in this scenario by switching to another app while Dozer's dock icon is hanging around. So, before activating the app, Dozer should check that it's still focused—otherwise just silently remove the icon like it does now.

**Comment by gingerbeardman** [comment]
Too much conjecture! 🤓

We need verified working methods.

**Comment by gingerbeardman** [comment]
`debugPrint(NSRunningApplication.current)`

Shows Dozer is the active app with all interactions I have tested so far.

Will try to find a code path that runs earlier just to confirm. Not hopeful.

**Comment by gingerbeardman** [comment]
```swift
let runningApp = NSWorkspace.shared.frontmostApplication
```
shows the previously active app.

**Comment by gingerbeardman** [comment]
OK, this is done and in #121 and I found and fixed another bug on the way!
