### ISSUE TITLE
Brew install for v4.1.0

### ISSUE THREAD

**Issue by ianhomer** [Mortennn/Dozer#112]
I noticed that the homebrew cask for dozer is still at v4.0.0 - https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dozer.rb

I tried to raise a request to update brew version with the process at https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md

I ran 

`cask-repair dozer`

and choose version 4.1.0, however I received the error

Error: Download failed on Cask 'dozer' with message: Download failed: https://github.com/Mortennn/Dozer/releases/download/v4.1.0/Dozer.4.1.0.dmg

It looks like the latest release download URL does not have a "v" in it now, it is available at https://github.com/Mortennn/Dozer/releases/download/4.1.0/Dozer.4.1.0.dmg.

Previous versions had a "v" in the version path in the URL, e.g. https://github.com/Mortennn/Dozer/releases/download/v4.0.0/Dozer.4.0.0.dmg

Is this URL change intentional and will future releases be available at URLs without a "v" in the version path in the URL? If so I can raise a PR with homebrew-cask to update this.

**Comment by nabilfreeman** [comment]
4.1 is in pre-release - could be because of that?

**Comment by ianhomer** [comment]
OK - thx - I hadn't noticed that.

**Comment by core-code** [comment]
both 4.1 and 4.2 are marked as 'Pre-release' and therefore not fit for inclusion into Homebrew Cask.

@Mortennn can you confirm those releases are marked as 'Pre-release' intentionally? we've just removed version 4.2 from Homebrew Cask because of this: https://github.com/Homebrew/homebrew-cask/pull/85985

**Comment by Mortennn** [comment]
@core-code Yes, this is intentional. 4.2 will be released soon though.

**Comment by core-code** [comment]
thanks for the confirmation. that means we will continue to skip the releases marked as 'pre-release' and only add the 'latest releases' to homebrew-cask
