### ISSUE TITLE
'Hide status bar icons after 10 seconds' not working; Dot disappears at times on menu bar

### ISSUE THREAD

**Issue by Amw94** [Mortennn/Dozer#115]
'Hide status bar icons after 10 seconds' is checked, but seems to not be working. Also, I've noticed when not in use and icons are hidden, the main dot seems to disappear at times.

![Screen Shot 2020-06-15 at 7 43 29 PM](https://user-images.githubusercontent.com/49608346/84716410-05026700-af41-11ea-9a23-3ae5dac96834.png)

V 4.0.0
Mac OS High Sierra 
10.13.6

**Comment by gingerbeardman** [comment]
There's an outstanding bug where if you option+click a dot it will not hide the icons until you click the dot again manually.
