### ISSUE TITLE
Icon doesn't seem to adapt to Dark Mode

### ISSUE THREAD

**Issue by redlegend96** [Mortennn/Dozer#16]
The icon does not change to white on black when Dark Mode is activated in Mojave. Works fine in Light Mode.
<img width="456" alt="screenshot 2018-10-14 at 16 12 58" src="https://user-images.githubusercontent.com/44122234/46918680-c2022a80-cfcc-11e8-8555-a287290f1d58.png">

Also, the icon does not display at all when clicked to show hidden icons in Dark Mode.
<img width="523" alt="screenshot 2018-10-14 at 16 13 51" src="https://user-images.githubusercontent.com/44122234/46918683-c9293880-cfcc-11e8-8dc7-2c8991957a66.png">

**Comment by Mortennn** [comment]
Which version of Dozer are you running?

**Comment by redlegend96** [comment]
I'm running Dozer 1.1.2

**Comment by Mortennn** [comment]
Strange, I am trying to recreate the bug, but the icon behaves as expected.
Please let me know if I'm recreating it in the wrong way.

![skaermoptagelse 2018-10-14 kl 21 09 50](https://user-images.githubusercontent.com/34214574/46920985-1968c080-cff6-11e8-8c33-f2bad0d5bfd7.gif)

**Comment by redlegend96** [comment]
No you're doing it right... I don't understand...
![dozer gif](https://user-images.githubusercontent.com/44122234/46921247-d526f180-cff0-11e8-9fb1-cfbf187e37e5.gif)

**Comment by Mortennn** [comment]
Hmm... maybe some other app is blocking the notification which should be sent to Dozer every time the system theme changes (i see you have Avast installed). Please turn it off and let me know if that solved your issue.

**Comment by redlegend96** [comment]
I've uninstalled Avast completely, quit all the apps that you did not have in your menu bar and restarted Dozer, no luck.

**Comment by Mortennn** [comment]
Well, I will include an option to set the theme of Dozer manually. I will begin implementing this feature ASAP.

**Comment by redlegend96** [comment]
Thank you so much, that would be amazing !

**Comment by Mortennn** [comment]
The option is now implemented in v1.1.3. Additionally, does the "Change icon theme automatically" work on your machine?

**Comment by redlegend96** [comment]
It's working now, but still not correctly, it seems to have inverted since last time. By default, the circle is now white on black, which means that it is invisible in Light Mode. If I select "Change Icon theme automatically", it changes to a black circle, which means it is only visible in Light Mode. Finally, selecting the Dark Mode option makes the icon black on black, making it only visible in Light Mode.
It basically seems like the colours are inverted to what they should be when you select the option for that mode (black on black in Dark mode, and white on white in Light mode, instead of white on black in Dark and black on white in Light)

**Comment by Mortennn** [comment]
Alright, so the option "Change icon theme automatically" still doesn't work for you😕
"Change icon theme automatically" should only be unchecked to set a specific theme of the Dozer icon. So in your case, if you are using the macOS dark mode, the "Dark icon"-option should be unchecked.

**Comment by redlegend96** [comment]
Correct, that option still doesn’t work... Don’t understand why...

**Comment by Mortennn** [comment]
The icon should adapt to theme changes in version 2
