### ISSUE TITLE
Dozer hides full date and time information

### ISSUE THREAD

**Issue by en0mia** [Mortennn/Dozer#174]
When I hit the hide button, Dozer collapses the date and time box too.
<img width="755" alt="Screenshot 2022-06-25 at 10 59 44" src="https://user-images.githubusercontent.com/42026938/175766267-7b6e8716-c152-43c9-8ede-2b279b7cea79.png">
^ Not collapsed, displays the full date and time

<img width="608" alt="Screenshot 2022-06-25 at 10 59 58" src="https://user-images.githubusercontent.com/42026938/175766279-02a60c4c-930d-4308-b68c-7147d1769b69.png">
^ Collapsed, only displays the Day and the Time

Environment:
MacBook Pro (13-inch, M1, 2020)
macOS Monterey 12.4 (21F79)
Dozer at its latest version (4.0.0 (29))

**Comment by immadisairaj** [comment]
You could just change the option in "System Preferences" to show the complete Date Time (below picture)

<img width="361" alt="Screenshot 2022-06-26 at 14 51 40" src="https://user-images.githubusercontent.com/40348358/175807768-1f4973db-3f5c-4937-879b-62f0d1f5202b.png">

**Comment by en0mia** [comment]
Thanks @immadisairaj, I wasn't aware of that setting.
