### ISSUE TITLE
Auto Show/ Hide Icons on Hover

### ISSUE THREAD

**Issue by Kapocsi** [Mortennn/Dozer#177]
I am looking to develop this feature myself; the CONTRIBUTING file recommends I get @Mortennn's blessing. So... I am here doing that.

Also, I am pretty sure this has something to do with the h fact I am running the macOS be, ta but I cannot build the project due to a macOS build target error; whenever I change the setting to make it compatible with my mac, it gets reverted upon running `make build`. 
```
	/usr/bin/xcrun xcodebuild -project /Users/~/Projects/mac-apps/Dozer/Carthage/Checkouts/Sparkle/Sparkle.xcodeproj -scheme Sparkle -configuration Release -derivedDataPath /Users/~/Library/Caches/org.carthage.CarthageKit/DerivedData/14.1_14B47b/Sparkle/1.26.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/bq/q0qyg8x10vs3wwg7stcnml7r0000gn/T/Sparkle SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/~/Projects/mac-apps/Dozer/Carthage/Checkouts/Sparkle)
```

Please advise

**Comment by mreel** [comment]
This would be awesome, but considering this projects seems to be dead, I wouldn't count on getting a reply.
Instead I'd take a look at the license and figure out if you are able/allowed to fork it and effectively make another version with this feature. I'd love it!

Edit: took a quick look myself, I think you are allowed, though don't shoot me if I'm wrong
