### ISSUE TITLE
WHY NOT SWAP THE FUNCTION OF RIGHT CLICK AND LEFT CLICK?

### ISSUE THREAD

**Issue by chang2000** [Mortennn/Dozer#18]
Just as the title, this is for trackpad user. I am more willing to left-click to hide other icons and do right- click to enter the setting.  When using force touch trackpad, it's more comfortable to do left-click with one finger but not right click with two fingers.
Anyway, thanks for the project.

**Comment by chang2000** [comment]
Or adding a switching choice in the setting is also fine!

**Comment by Mortennn** [comment]
It will be changed in the next version, which I will be released in a few days.
