### ISSUE TITLE
Add (small, configurable) delay before showing items

### ISSUE THREAD

**Issue by LinusGeffarth** [Mortennn/Dozer#24]
First off, love the idea & simplicity of the app! :)

I'm working with multiple displays - that's my MacBook Pro, and two monitors arranged as follows:
<img width="266" alt="monitor setup" src="https://user-images.githubusercontent.com/9455439/47549900-c815d680-d8fd-11e8-89e2-e9b3b58eabd6.png">

Now, when switching to those monitors, I always activate Dozer to show the items.
For that, I'd propose to add a small & configurable delay. When triggered, the app should wait for like 0.5s and then check whether the pointer is still on the menubar and then determine whether or not it should display the items.

---

#22 would also be a solution to the issue.

**Comment by Mortennn** [comment]
#23 see my last comment :)

**Comment by LinusGeffarth** [comment]
Yayy! Thanks! :)
