### ISSUE TITLE
Dozer won't launch on macOS Sierra.

### ISSUE THREAD

**Issue by Mortennn** [Mortennn/Dozer#26]
Tried v2 and v2.1 and none launched. Are anybody else experiencing the same problem?

**Comment by eugenia1815** [comment]
Same here. Problem occurs for v2 and v2.1.

**Comment by eugenia1815** [comment]
And when i tried to delete and download the v1.1.3 and v1.1.2, both no longer worked on my MacBook.

**Comment by Mortennn** [comment]
Hmm, I think I am just going to say that macOS Sierra is unsupported then😕
