### ISSUE TITLE
Some menu bar applications doesn't work

### ISSUE THREAD

**Issue by tatecapone** [Mortennn/Dozer#28]
Some applications in the menu-bar and that opens by shortcuts, if they are hidden by dozer they simply do not respond (for example snippetsLab) and others like the translator 'Mate Translate', they open in any rare part of the screen. If you show dozer and then run those applicationes, there is no problem ... Maybe to have an account in the future.
Again...THANKS FOR DOZER!!!

**Comment by Mortennn** [comment]
I see. I will definitely try to fix this to the next update. Thanks for reporting :)

**Comment by tatecapone** [comment]
It is not very important, because when you open Dozer through its shortcuts and then invoke the application you want to use, everything works correctly. Regards!

**Comment by Mortennn** [comment]
There are not anything that can be done which would make sense, so I will just close this for now. You are open to reopen if you wish.
