### ISSUE TITLE
'Autohide on startup' option

### ISSUE THREAD

**Issue by kbysiec** [Mortennn/Dozer#29]
Hi,

First off all I would like to thank you for great app!

It would be perfect if you could add option to preferences to allow autohide on startup of app.

Thank you one more time for your effort.

**Comment by inomoz** [comment]
Maybe also autohide after timeout (N seconds).

**Comment by joshkmartinez** [comment]
I second this! Maybe, in addition, add an auto-hide option, so after a couple of seconds, the menu would auto-close. Thanks for making a great app! 👍

**Comment by RafalBuchner** [comment]
I would love it!!!

**Comment by Cariffo** [comment]
oh yes that would be amazing... great app!
but that autohide option would make it even better, i have to manually hide my unimportant apps on every startup now :D

**Comment by grokcodile** [comment]
I came here looking to make the same feature request. I hacked together my own solution that uses Automator to launches dozer and then send the keyboard command sequence to hide/show icons that you can set in the app preferences. This gives me the same end effect. Launches Dozer and then hides the icons. I add that Automator script in the launch items and remove Dozer.

**Comment by cqwt** [comment]
I wrote a short tutorial about how to use AppleScript to launch Dozer at login and send key code (your shortcut) to hide the menu items.
https://github.com/cqwt/dozer-autohide-applescript

**Comment by grokcodile** [comment]
Nice solution! Thank you!

--  
Ethan H. Darling | (802) 321-0384

**Comment by aonez** [comment]
Quick build from #78: [Dozer.zip](https://github.com/Mortennn/Dozer/files/3749699/Dozer.zip)

**Comment by aonez** [comment]
Quick build (properly signed) for #78 with hide on launch: [Dozer.zip](https://github.com/Mortennn/Dozer/files/3751062/Dozer.zip)

**Comment by AndrewMast** [comment]
@Mortennn This was covered in aonoz's #78, right?
