### ISSUE TITLE
Unhides on Mouse Press Up instead of Down

### ISSUE THREAD

**Issue by andrewOOP** [Mortennn/Dozer#31]
If I click something on screen that's not the menubar, and then I let go of the click on the menu bar, it unhides the icons. This happens to me a lot, and it could be fixed by having Dozer unhide on Mouse Down on the blank menu bar instead of on Mouse Up.

**Comment by Mortennn** [comment]
This should be fixed in version 2.2.0. Thanks for reporting😀
