### ISSUE TITLE
Update 2.2.0....Macos Mojave

### ISSUE THREAD

**Issue by tatecapone** [Mortennn/Dozer#34]
There is an error installing update.
![captura de pantalla 2018-11-26 a la s 22 13 53](https://user-images.githubusercontent.com/38765698/49051917-94fa8780-f1c8-11e8-90f0-62461ebd82b6.png)

**Comment by Mortennn** [comment]
I just double checked, but I don't experience any problems updating. Is can you please try again and reopen if it is still a problem? :)

**Comment by tatecapone** [comment]
Another problem is downloading the dmg ... start to appear error windows one after another and you have to restart the application

**Comment by tatecapone** [comment]
The update error persist
![captura de pantalla 2018-11-27 a la s 14 56 52](https://user-images.githubusercontent.com/38765698/49101356-bf922200-f254-11e8-81ff-aa142b80fbd5.png)

**Comment by tatecapone** [comment]
I try to restart the computer and nothing ... I'm going to do a cleaning cache and permissions and tell you.

**Comment by Mortennn** [comment]
Alright. If it still fails, just download the app directly from Github and replace it with the old one.

**Comment by tatecapone** [comment]
Another problem is downloading the dmg ... start to appear error windows one after another and you have to restart the application

**Comment by Jackymancs4** [comment]
Hello @Mortennn 
I'm experiencing the same issue in MacOS High Sierra 10.13.6 (17G3025).

<img width="424" alt="schermata 2018-11-28 alle 11 56 16" src="https://user-images.githubusercontent.com/6209647/49147574-59190c80-f305-11e8-8f29-d5e1c19c24c3.png">

> Alright. If it still fails, just download the app directly from Github and replace it with the old one.

So I've done it, and it resulted in what I think @tatecapone was also experiencing.

<img width="854" alt="schermata 2018-11-28 alle 11 58 11" src="https://user-images.githubusercontent.com/6209647/49147682-967d9a00-f305-11e8-9a03-ea034a7f45e0.png">

To fix it, I opened the accessibility settings with Dozer closed. Manually **removed** dozer entry, and then launched it again.

Not sure what is goin on, but maybe you'll want to add an installation/update note to the readme.

**Comment by Mortennn** [comment]
That really doesn't look good. I will indeed start implementing a better onboarding.

**Comment by tatecapone** [comment]
> Hello @Mortennn
> I'm experiencing the same issue in MacOS High Sierra 10.13.6 (17G3025).
> 
> <img alt="schermata 2018-11-28 alle 11 56 16" width="424" src="https://user-images.githubusercontent.com/6209647/49147574-59190c80-f305-11e8-8f29-d5e1c19c24c3.png">
> 
> <img alt="schermata 2018-11-28 alle 11 58 11" width="854" src="https://user-images.githubusercontent.com/6209647/49147682-967d9a00-f305-11e8-9a03-ea034a7f45e0.png">
> 
> To fix it, I opened the accessibility settings with Dozer closed. Manually **removed** dozer entry, and then launched it again.

it worked for me!!!
Thanks!
