### ISSUE TITLE
Dozer sometimes requests permission to use accessibility even with permissions already given

### ISSUE THREAD

**Issue by tatecapone** [Mortennn/Dozer#37]
dozer 2.2.1, every so often the following window appears, with the permissions ok
![captura de pantalla 2018-11-30 a la s 14 31 20](https://user-images.githubusercontent.com/38765698/49305064-f06c9400-f4ac-11e8-9265-b1cb6f0e2626.png)

**Comment by tatecapone** [comment]
Yes, it keeps showing up every so often. Even if I remove dozer from accessibility and add it again.
Mcaos Mojave, lastest update.

**Comment by Mortennn** [comment]
I am not able to recreate the issue😕 I think I will try to work on a workaround, so Dozer does not depend on the accessibility kit. Thanks for reporting👍

**Comment by tatecapone** [comment]
Ok...thank you for your kindness

**Comment by Mortennn** [comment]
v2.2.2 should solve this issue. Please let me know if it doesn't😀

**Comment by tatecapone** [comment]
For now everything works wonders. You are a genious. Dozer Rocks !!
