### ISSUE TITLE
Firefox menus stop working properly

### ISSUE THREAD

**Issue by Jcrs** [Mortennn/Dozer#40]
First of all, thanks for this awesome app!

There seems to be an issue with Firefox (stable, beta or nightly) when dozer is running. 

The menus and drop-downs just stop working properly. You can access some drop-downs by trial and error or double tapping. I've tried to remove / stop several add ons to make sure it wasn't some weird incompatibility to no avail.  

I've create a gif which you can see the weird behaviour. 

![ff_with_dozer](https://user-images.githubusercontent.com/1193343/49662903-f92d0f00-fa44-11e8-8af2-9cf211705dc7.gif)

I'm using 63.0.3 (64-bit) but tried with the nightly builds as well.

Cheers!

**Comment by Mortennn** [comment]
I am actually already working on a solution because it is also present in some other apps. I think it is finished in about 10 days. Please be patient and thank you for the compliment😀

**Comment by Jcrs** [comment]
Thanks for the quick reply! 

Awesome I’ll wait, thank you for your work! 😃

**Comment by Mortennn** [comment]
@Jcrs The issue should be resolved in version 3😀

**Comment by Jcrs** [comment]
Wow, awesome! thanks you! 🥳
