### ISSUE TITLE
Welcome screen don't close after clicking on continue button. 

### ISSUE THREAD

**Issue by tikkerei** [Mortennn/Dozer#42]
Version: 3.0.0
MacOS Mojave 10.14.2 (18C54) on Macbook Pro 13" 2015 Late

Hey, first thank for the update @Mortennn !
In the last version welcome screen don't close after clicking on continue button. 

<img width="631" alt="screenshot 2018-12-11 at 22 25 22" src="https://user-images.githubusercontent.com/224665/49831228-ada39980-fd93-11e8-8abc-a60a9a80bc2e.png">

**Comment by 3zero2** [comment]
Confirmed here as well.

**Comment by Jcrs** [comment]
@Mortennn still not working on v3.0.1, for me.

**Comment by oswaldcameron** [comment]
@Jcrs hold CMD and drag the left dot next to the right dot. 

The logic is anything to the left of the dot disappears. Anything to the right, stays. I felt it was more intuitive, before, but I don't mind it this way either.

**Comment by oswaldcameron** [comment]
Downloaded 3.0.1 and still—pesky dialog window won't close.

**Comment by Mortennn** [comment]
The welcome screen is disabled in v3.0.2. I apologize!

Having two dots solves a lot of issues, which were present in v2.2.2. I agree it is less intuitive, but it just solves a lot of problems, so I decided it was well worth it.
