### ISSUE TITLE
Two Dozer on Memubar

### ISSUE THREAD

**Issue by ShoyuWeenie** [Mortennn/Dozer#44]
For some reason, I have two Dozer on my menubar after updating from Dozer 2.2.2 to Dozer 3.0.1:

<img width="312" alt="screen shot 2018-12-11 at 4 13 08 pm" src="https://user-images.githubusercontent.com/5351836/49842467-8ab3be00-fd70-11e8-9149-de98b5faa495.png">

**Comment by tatecapone** [comment]
I have the same problem.
In addition, the icons of the applications are not and the dozer welcome screen is impossible to close. Excellent app, keep working! Thank you!
![captura de pantalla 2018-12-12 a la s 00 06 40](https://user-images.githubusercontent.com/38765698/49844513-18f46800-fda2-11e8-901c-581966b24779.png)
![captura de pantalla 2018-12-12 a la s 00 09 01](https://user-images.githubusercontent.com/38765698/49844529-2873b100-fda2-11e8-9bc6-be36f18407b5.png)

**Comment by tatecapone** [comment]
The doble dozer continue, and the app doesnot gidden. Doesn´t work.

**Comment by Jcrs** [comment]
What if you change one of the dots (transparent, shape?) so it's a bit more clearer ? 

As a suggestion, you could include an image on the Welcome screen with instructions ?

**Comment by Mortennn** [comment]
> What if you change one of the dots (transparent, shape?) so it's a bit more clearer ?


They are the same because it doesn't matter which one you put on the left. But I will take a look at other design possibilities.

> As a suggestion, you could include an image on the Welcome screen with instructions ?

I agree. I will do it as soon as possible.

**Comment by Kartal1903** [comment]
Is this a new feature you added? Or is it an temporary issue? I really liked how it worked before, one of the best apps.

**Comment by Kartal1903** [comment]
> Is this a new feature you added? Or is it an temporary issue? I really liked how it worked before, one of the best apps.

You could maybe add an option to chose between how it previously worked vs how it works now.

**Comment by ShoyuWeenie** [comment]
Thanks for the clarification. I agree that there could be someway to differentiate the two dozers - one circle, the other dot. Also, keep up the great work!

**Comment by andreykats** [comment]
Please add an option to not show any dots in the "collapsed" state.

**Comment by 3zero2** [comment]
Agreed. Having two DoZer icons is not very intuitive.

In fact I was going to open an issue about it because if a user decides to keep the dozer icon to the left, then two dozer icons will appear next to each other when the menu bar  icons are shown. 

However I read somewhere that having two icons solved a number of other issues so I don't know what to think now.

**Comment by Mortennn** [comment]
I am aware that this is less intuitive than only having one icon like it was before. However, there are a lot of limitations in macOS, which meant that some of the critical issues in v2.2.2 could not be fixed, without having to do some too hacky stuff, which properly would cause more issues.

I am sorry this is not the ideal way of hiding the menu bar icons, but I feel like I have to prioritize stability. Personally, I do not think this that bad. I have most of my menu bar icons hidden all the time, so I only have one Dozer icon visible most of the time, which in my opinion is fine.

> Please add an option to not show any dots in the "collapsed" state.

@andreykats  This is definitely possible if you then use a shortcut to show the icons again. I will implement this in the near future.

> In fact I was going to open an issue about it because if a user decides to keep the dozer icon to the left, then two dozer icons will appear next to each other when the menu bar icons are shown.

@3zero2 I am not sure I understand this correctly. Can you please elaborate?

> You could maybe add an option to chose between how it previously worked vs how it works now.

@Kartal1903 That could indeed be an option and then mark it as "experimental" or something. I will consider this.

**Comment by Vidhin05** [comment]
I personally prefer the 2.2.2 version of Dozer, I don't like the extra dot on my menu bar

**Comment by aka7z** [comment]
is it possible to downgrade to ver.2 and how?

**Comment by Mortennn** [comment]
https://github.com/Mortennn/Dozer/releases/download/2.2.2/Dozer.2.2.2.dmg

**Comment by tatecapone** [comment]
> CMD+drag the left icon between some menu bar icons. Click one of the icons to hide all icons on the left side of the Dozer icon to the left. Hope that makes sense, else take a look at the demo on the main page.

very Thnks for the instructions. I love the new dozer implementation!!

**Comment by Mortennn** [comment]
Glad to hear😀

**Comment by wright96d** [comment]
> > Please add an option to not show any dots in the "collapsed" state.
> 
> @andreykats This is definitely possible if you then use a shortcut to show the icons again. I will implement this in the near future.

Really loving the app, but I do wish collapsed to be clean as possible. Do you have an update on when this feature will be available?

**Comment by Mortennn** [comment]
@wright96d A new version will be released in about a week. Then, this feature will be implemented.
