### ISSUE TITLE
Bitbar moves to hiding zone

### ISSUE THREAD

**Issue by onoma2** [Mortennn/Dozer#47]
Hello, thank you for the app. Everything is working as intended, but Bitbar scripts keep moving themselves to hiding zone after Sleep/Reboot. 
So you need to drag them out of the zone one more time

**Comment by Mortennn** [comment]
Okay👍

**Comment by gingerbeardman** [comment]
+1 to solve this

The issue is that when BitBar refreshes, it destroys all menu bar icons and then rebuilds them.
