### ISSUE TITLE
Dozer icons not expanding

### ISSUE THREAD

**Issue by NRauh** [Mortennn/Dozer#48]
Since the update that added two icons, when I click an icon to show the hidden icons, that icon gets hidden, and I'm unable to expand them (even with a shortcut).

**Comment by Mortennn** [comment]
If you cannot get the hidden icons shown again then go to **Activity Monitor > Search for Dozer > Close it**

Try to reproduce the issue and tell me what you did.

**Comment by NRauh** [comment]
Here's a recording of it happening: https://imgur.com/JCVdVkU (not obvious is that I'm clicking the icon twice).

1. Open Dozer
1. Click right icon to collapse
1. Click icon again to expand

It seems to be happening regardless of how I collapsed it (via clicking left icon or keyboard shortcut).

Using the keyboard shortcut to hide and show seems to work fine though.

I've tried reinstalling with brew cask and downloading from GitHub.

**Comment by Mortennn** [comment]
Are you using multiple monitors?

**Comment by NRauh** [comment]
Yes, I'm using two external and the built in Macbook display.

I quickly tried it out, and it seems to work fine with one or two monitors, but not with the third.

**Comment by codrake** [comment]
I have the same issue and only using the laptop screen. The way I can reproduce it every time is to use the right-most icon to collapse/hide items. Unable to reproduce it by hiding icons by using the left icon.

**Comment by EnricoMonese** [comment]
Same issue, using two monitors

**Comment by Mortennn** [comment]
Could one of you share a screenshot of the display layout you are using?

**Comment by NRauh** [comment]
![Here's a screenshot of the arrangement in my settings.](https://user-images.githubusercontent.com/3896310/50301805-e9062e00-044d-11e9-8d14-b69462c58c02.png)

Is that what you asked for?

**Comment by NRauh** [comment]
I noticed that it works fine when expanding on the built in monitor with the others plugged in.

**Comment by Mortennn** [comment]
I have tried to reproduce the issue, but with no luck😕
Therefore, I have created a test release with changes that I suspect might cause the issue.
Please download it manually [here](https://github.com/Mortennn/Dozer/releases/tag/v3.0.3) and let me know if it solves your issues😀

**Comment by codrake** [comment]
The update resolved the issue in my setup. Thanks!

**Comment by NRauh** [comment]
Seems to work for me too. I'm going to close this issue then.

**Comment by Mortennn** [comment]
Glad to hear it's working.
