### ISSUE TITLE
There's 2 Dozer icons at the menu bar...

### ISSUE THREAD

**Issue by SwayChen** [Mortennn/Dozer#49]
![image](https://user-images.githubusercontent.com/6345749/50320433-48744480-0507-11e9-9967-86c91a7416ff.png)

Model: Macbook Pro 13
System: Mojave 10.14.1 (18B75)

Have tried `brew cask uninstall dozer` & reinstall, but still 2 dozer icons

**Comment by Mortennn** [comment]
See my explanation [here](https://github.com/Mortennn/Dozer/issues/44#issuecomment-446715099)
