### ISSUE TITLE
Its not working on Mac 10.14.2

### ISSUE THREAD

**Issue by Tarunn** [Mortennn/Dozer#50]
I have installed the app on my Mac 2018 model 15 inch.
Post installation only 2 round icons appear at top and nothing happens on clicking on them.
Please fix this as due to this the app is just not usable .

**Comment by Mortennn** [comment]
Please reopen if the issue persists.

**Comment by McRosbeef** [comment]
Same here ! Not working at all on 10.14.3
I dragged some icons between the dots but nothing happens. Only one dot disapear.

**Comment by Mortennn** [comment]
Does it still not work when you do [this](https://raw.githubusercontent.com/Mortennn/Dozer/master/demo/demo.gif)?

**Comment by x-ji** [comment]
I did the same as @McRosbeef and only realized the correct way to use Dozer after your comment.

IMO this is a bit unintuitive. The design of "two dots" naturally makes people want to put the icons to hide between them, not to the left of **both** of them.

Maybe there could be some clarification in the README about the correct way to use Dozer?
