### ISSUE TITLE
Do this show the icons when they change (e.g. notification happen)?

### ISSUE THREAD

**Issue by ciaoben** [Mortennn/Dozer#52]
Like the title :)

**Comment by Mortennn** [comment]
Dozer does not detect any changes in other apps. It only hides the icons.

Does this answer your question?

**Comment by ciaoben** [comment]
@Mortennn yeah for sure! thanks!

**Comment by zhyiyu** [comment]
Though, it would be wonderful if it does offer that feature! Great app, thanks!
