### ISSUE TITLE
Resize dot icon

### ISSUE THREAD

**Issue by asfork** [Mortennn/Dozer#56]
Maybe the dot icon should be resized. It is too obvious on the Menu Bar.
See below “distraction-free” idot. 

![idot1](https://user-images.githubusercontent.com/6972631/52051475-ab3d0f00-258e-11e9-86fc-dbee2d2e7349.png)

![idot2](https://user-images.githubusercontent.com/6972631/52051481-af692c80-258e-11e9-8195-f31d1d98a41c.png)

**Comment by glowacky** [comment]
Perhaps dot size could be an option for users to select in Preferences?

**Comment by alienator88** [comment]
As a workaround, I edited the Assets.car archive and scaled the dot image file down 50%.
1. Quit the Dozer app.
2. Navigate to: Dozer.app > Contents > Resources. 
3. Rename Assets.car to Assets.car.bk for safe keeping.
4. Extract the Assets.car file in this zip and drop it in the Resources folder.
5. Profit!

@Mortennn If this is not okay, feel free to delete the comment.
Take care everyone.

[Assets.car.zip](https://github.com/Mortennn/Dozer/files/3168104/Assets.car.zip)

**Comment by singularitti** [comment]
I would vote for a resize of dot icon because of it is taking much space. I want to shrink it to show more other apps.

**Comment by timothy-morph** [comment]
Resize the dot or be able to change the icon will be perfect !! :D
and thanks for making this great app, it's super helpful.

**Comment by Quickshadoww** [comment]
+1 for resize icon

**Comment by gingerbeardman** [comment]
This can be closed.
