### ISSUE TITLE
Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/dozer

### ISSUE THREAD

**Issue by frinsen** [Mortennn/Dozer#57]
I had problems using the brew command "brew cask install dozer"

See log:
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://github.com/Mortennn/Dozer/releases/download/v3.0.4/Dozer.3.0.4.dmg
Already downloaded: /Users/martinfrindt/Library/Caches/Homebrew/downloads/2453eec7a50e3a57840474721f9933a16583d7d714d8de55cc7399858cab6696--Dozer.3.0.4.dmg
==> Verifying SHA-256 checksum for Cask 'dozer'.
==> Installing Cask dozer
==> Purging files for version 3.0.4 of Cask dozer
Error: Permission denied @ dir_s_mkdir - /usr/local/Caskroom/dozer
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:576:in `mkpath'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:119:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:140:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:124:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:184:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:72:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'

**Comment by Mortennn** [comment]
Please try the following:

`brew update && brew cleanup && brew cask cleanup && brew cask install dozer`

Does the issue persist?

**Comment by frinsen** [comment]
iFrindtPro:~ martinfrindt$ brew update && brew cleanup && brew cask cleanup && brew cask install dozer
Already up-to-date.
Warning: Skipping fish: most recent version 3.0.1 not installed
Warning: Skipping git: most recent version 2.20.1 not installed
Warning: Skipping htop: most recent version 2.2.0_1 not installed
Warning: Skipping imagemagick: most recent version 7.0.8-26 not installed
Removing: /Users/martinfrindt/Library/Caches/Homebrew/imagemagick--7.0.8-16.mojave.bottle.tar.gz... (8.5MB)
Warning: Skipping libpng: most recent version 1.6.36 not installed
Removing: /Users/martinfrindt/Library/Caches/Homebrew/libpng--1.6.35.mojave.bottle.tar.gz... (444.6KB)
Warning: Skipping libtiff: most recent version 4.0.10_1 not installed
Warning: Skipping mas: most recent version 1.6.2 not installed
Removing: /Users/martinfrindt/Library/Caches/Homebrew/openjpeg--2.3.0.mojave.bottle.tar.gz... (2MB)
Warning: Skipping pandoc: most recent version 2.6 not installed
Warning: Skipping smartmontools: most recent version 7.0 not installed
Warning: Skipping webp: most recent version 1.0.2 not installed
Removing: /Users/martinfrindt/Library/Caches/Homebrew/webp--1.0.1.mojave.bottle.tar.gz... (852.3KB)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/libtiff... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/libtool... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/little-cms2... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/libpng... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/freetype... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/openjpeg... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/webp... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/xz... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/jp2a... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/pcre2... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/jpeg... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/imagemagick... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/fish... (64B)
Removing: /Users/martinfrindt/Library/Logs/Homebrew/telnet... (64B)
Pruned 0 symbolic links and 1 directories from /usr/local
==> This operation has freed approximately 11.8MB of disk space.
Homebrew Cask provides a friendly CLI workflow for the administration
of macOS applications distributed as binaries.

Commands:

    audit      verifies installability of Casks
    cat        dump raw source of the given Cask to the standard output
    create     creates the given Cask and opens it in an editor
    doctor     checks for configuration issues
    edit       edits the given Cask
    fetch      downloads remote application files to local cache
    home       opens the homepage of the given Cask
    info       displays information about the given Cask
    install    installs the given Cask
    list       with no args, lists installed Casks; given installed Casks, lists staged files
    outdated   list the outdated installed Casks
    reinstall  reinstalls the given Cask
    style      checks Cask style using RuboCop
    uninstall  uninstalls the given Cask
    upgrade    upgrades all outdated casks
    zap        zaps all files associated with the given Cask

See also "man brew-cask"
Error: help does not take arguments.

**Comment by Mortennn** [comment]
`brew cask cleanup` is deprecated - my bad.
Please try `brew cask install dozer` again.

**Comment by frinsen** [comment]
not working for me - same error. I installed it via the DMG download

**Comment by Mortennn** [comment]
Alright. I think the issue is related to Homebrew.
Hope you like it :)

**Comment by claudioabreu** [comment]
I had the same problem installing Insomnia. I realized that the folder /usr/local/Caskroom had the wrong proprietary, **501**:staff. To solve this, run the command `sudo chown {user}:staff /usr/local/Caskroom`, where {user} is your username.

**Comment by sumanreddyk** [comment]
Thank You! @Mortennn.. It worked perfectly fine for me.

**Comment by tvial-tagheuer** [comment]
`sudo chown $(whoami):staff /usr/local/Caskroom` should work work everyone.
