### ISSUE TITLE
When the computer with an external monitor is turned on, the app does not respond.

### ISSUE THREAD

**Issue by JiangWenqi** [Mortennn/Dozer#60]
Hi,

First off all I would like to thank you for great app!

But when my computer with an external monitor is turned on, the software does not respond, even jams, and **disappears** on the status bar. Other software (started, hidden, like `cleanMyMacX`) disappears on the status bar too.

When I don't pick up the monitor, there is no such problem.

Thank you one more time for your effort.

**Comment by Mortennn** [comment]
Try rearranging your monitor layout. Does that change anything?

**Comment by JiangWenqi** [comment]
Thank you for your reply
After I tried again many times, I found that the problem disappeared. This may be a coincidence.
