### ISSUE TITLE
Nothing is hiding

### ISSUE THREAD

**Issue by aleminopuy** [Mortennn/Dozer#61]
I have it installed in Applications and have the dozer icons surrounding other menu bar icons. When I click one of them, the leftmost dozer icon disappears, but that's it. Everything else is still there!

My Menu Bar: 
![nobody's going anywhere!](https://i.imgur.com/BjDbsXe.gif "My Menu Bar")

Running macOS Mojave 10.14.3 - am I doing something wrong? Does accessibility access need to be granted or something like that?

**Comment by Mortennn** [comment]
Move the left Dozer icon in between some other icons :)
