### ISSUE TITLE
Is anything change?

### ISSUE THREAD

**Issue by maxming2333** [Mortennn/Dozer#64]
4 months, there are a lot of issues, but the software has not had a new release version.
Looks like the author has no idea to continue to maintain

**Comment by Mortennn** [comment]
Sorry for the delay. 
There will be a new version in about a week.

**Comment by sogen** [comment]
> 4 months, there are a lot of issues, but the software has not had a new release version.
> Looks like the author has no idea to continue to maintain

It's free
