### ISSUE TITLE
A slight CPU usage jump after updating to 3.0.5

### ISSUE THREAD

**Issue by mustafawm** [Mortennn/Dozer#65]
Noticed Dozer started showing up on CPU top 5 consumers list (screen shot from iStats) after the last update (v 3.0.5) 

<img width="292" alt="Screen Shot 2019-04-16 at 8 25 58 pm" src="https://user-images.githubusercontent.com/13101565/56202391-3efa8380-6086-11e9-94c9-2dadead0e3d0.png">

> Not a significant deal though

**Comment by mustafawm** [comment]
closing...not an issue.

**Comment by Wdavery** [comment]
This should be reopened, definitely an issue for me as well.

**Comment by Mortennn** [comment]
@Wdavery Does the problem persist if you restart Dozer?

**Comment by Wdavery** [comment]
Does not persist.

**Comment by Mortennn** [comment]
Great! The issue is related to the welcome screen not being closed properly. It will get fixed in the next release.

**Comment by mustafawm** [comment]
Thanks @Mortennn 
You can close this once the fix is pushed.

**Comment by mustafawm** [comment]
Also FYI https://dozermac.com still offers 3.0.4 version

**Comment by Mortennn** [comment]
That's fixed now. Thank you 👍

**Comment by mustafawm** [comment]
Hi @Mortennn  any update on this issue?

**Comment by Mortennn** [comment]
In my testing, the issue is fixed in master.

Checkout [CONTRIBUTING.md](https://github.com/Mortennn/Dozer/blob/master/CONTRIBUTING.md#getting-started) on how to build Dozer.

I will close this issue once the new version of Dozer is released.

**Comment by mustafawm** [comment]
Built and ran it for a while, seems to be working fine 👍
