### ISSUE TITLE
Add possibility to hide the dot icon

### ISSUE THREAD

**Issue by surdu** [Mortennn/Dozer#70]
It would be nice that once you set a keyboard shortcut, to be able to hide the dot used to toggle the visibility of the icon, and show it only when you show all the icons.

You can also hide it completely, and use the other dot to access Dozer options.

**Comment by Mortennn** [comment]
This is available in `master`.

Checkout [CONTRIBUTING.md](https://github.com/Mortennn/Dozer/blob/master/CONTRIBUTING.md#getting-started) on how to build Dozer.
