### ISSUE TITLE
Reboot resets the icon positions

### ISSUE THREAD

**Issue by TyrannosaurHex** [Mortennn/Dozer#74]
Are the icons supposed to reset to outside the dozer dots after every reboot? Not sure if this is a bug or intended behaviour. I'm on Mojave 10.14.6.

**Comment by Mortennn** [comment]
Dozer has no control over the positions of the status bar icons so this is all done by macOS.

**Comment by AndrewMast** [comment]
I also have this problem. Do you know of any way to stop macOS from rearranging the icons?

**Comment by Mortennn** [comment]
Unfortunately not :(

**Comment by AndrewMast** [comment]
I think I might have found something that may contribute to this issue.

Running `defaults read com.mortennn.Dozer` outputs in this (notice the preferred positions):
```
{
    "NSStatusItem Preferred Position Item-0" = "161.5";
    "NSStatusItem Preferred Position Item-1" = "486.5";
    "NSStatusItem Preferred Position Item-2" = "161.5";
    "NSWindow Frame com.sindresorhus.Preferences.FrameAutosaveName" = "784 342 397 303 0 0 1440 877 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2019-10-04 22:32:00 +0000";
    SUSendProfileInfo = 0;
    hideAfterDelayEnabled = 1;
    noIconMode = 1;
    removeStatusIconEnabled = 1;
    toggleMenuItems = <...>;
}
```

I noticed the preferred positions and the lack of the names (aka remove, normalLeft, normalRight) and I quit and restarted Dozer and the remove icon and one of the normal ones swapped. Maybe (I don't know how they are stored currently) saving the preferred positions with the names would fix some of it?

**Comment by AndrewMast** [comment]
Maybe setting the `NSStatusItem.autosaveName` will solve this issue?

**Comment by amarendra** [comment]
Is it related to #69 

Or there any additional script one can run to make it happen?

**Comment by Mortennn** [comment]
@amarendra Yes, this is related to #69.

**Comment by Mortennn** [comment]
I will close this for now because it is not something Dozer has control over.
