### ISSUE TITLE
Donations/Tips

### ISSUE THREAD

**Issue by bcye** [Mortennn/Dozer#77]
Hi,

I really like the project, great work!

Do you have a buymeacoffee.com page, or some way to pay for the app?

**Comment by Mortennn** [comment]
Hi @bcye,

Thank you! I am glad you like Dozer. 

I do have a BMC page: https://www.buymeacoffee.com/mortennn

**Comment by bcye** [comment]
Cheers!
<img width="1680" alt="Screenshot 2019-09-23 at 23 32 09" src="https://user-images.githubusercontent.com/29666239/65464605-7f8ed200-de5a-11e9-9e02-60fa0d0f9a72.png">
