### ISSUE TITLE
Hide status bar icons after 10 seconds sometimes does not work

### ISSUE THREAD

**Issue by zhouxingchijared** [Mortennn/Dozer#83]
I'm on macos 10.15.1 (19B88),  dozer on 4.0.0, hide status bar icons after 10 seconds sometimes does not work.

**Comment by AndrewMast** [comment]
This might have been solved in the merged pull request #78, but it hasn't been released in a version yet

**Comment by gingerbeardman** [comment]
I have also found this and can reproduce it.

## Reproduce
1. this option should be checked/on: Enable 'remove' Dozer icon
2. Alt+Click the right most Dozer dot

## Expected
- icons should disappear after a time

## Actual
- icons stay visible always

## Workaround
- click the dozer dot to hide the icons
