### ISSUE TITLE
Why is this app sending data thought the network ?

### ISSUE THREAD

**Issue by morsamatias** [Mortennn/Dozer#88]
I have recently installed Dozer and the activity monitor say:
Bytes sent 8KB 
Bytes received 22KB

**Comment by eduardoalire** [comment]
no comments? 🤔

**Comment by morsamatias** [comment]
Its strange, I don't have time to read the hole code, so it will be really useful if some developer help us to clarify this topic

**Comment by eduardoalire** [comment]
I think this could be due to the auto-update check... I don't see any other feature to work with data

**Comment by morsamatias** [comment]
Cool, thank you.

**Comment by morsamatias** [comment]
Is there any way to disable the auto-check?

**Comment by tplk** [comment]
@morsamatias right-click one of the icons to open the settings, you'll find the toggle there.
![image](https://user-images.githubusercontent.com/20531968/69620927-2eb07b00-104f-11ea-8b6a-ca6a31fee515.png)

**Comment by morsamatias** [comment]
@tplk @eduardoalire  I have uncheck the option to Automatically check for updates but stills is sending data through the network. 22 KB sent, 19 KB received. What data is sending?

**Comment by eduardoalire** [comment]
I don't know. To be honest, the only way to know what data is sending is a reply from the creator, or to dive deeply into the code.

Maybe the auto-updater even when disabled, is checking for updates. Who knows 🤷🏽‍♂️

**Comment by grafviktor** [comment]
Probably that sparkle which is used to check for updates generates this network activity.

**Comment by ajkblue** [comment]
I also have autoupdating turned off on mine, so the other traffic that you see might be from crashlytics (according to Little Snitch):
<img width="332" alt="Screen Shot 2019-12-18 at 10 15 04 AM" src="https://user-images.githubusercontent.com/9651939/71107952-53e06700-217f-11ea-9985-b338f61f96e0.png">

**Comment by morsamatias** [comment]
@ajkblue Cool, thank you!
