### ISSUE TITLE
It's not work on MacOS Catalina

### ISSUE THREAD

**Issue by XanderXu1998** [Mortennn/Dozer#89]

**Comment by pnodet** [comment]
I'm running Dozer on macOS Catalina without any major trouble.
Could you provide more informations ?
What Catalina build are you running ?

**Comment by XanderXu1998** [comment]
Now it works. I don't know what happen........

**Comment by qindj** [comment]
You have to open Dozer once from launchpad after your Mac upgrade to Catalina.
Remember to check the "Launch at login" in General tab

**Comment by yermulnik** [comment]
macOS Catalina 10.15.5
dozer: 4.2.0 (auto_updates)
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1274789/87435387-595a3e80-c5f4-11ea-8bf1-249c1213ca84.png">

**Comment by yermulnik** [comment]
As a workaround I had to right-click and choose Open.

**Comment by Mortennn** [comment]
@yermulnik The reason is that the binary is not notarized because I have trouble doing so. The final release will hopefully be notarized.

**Comment by yermulnik** [comment]
@Mortennn Thanks for info and thanks for the great tool.
