### ISSUE TITLE
No way to set option+shift+alphabet e.g. ⌥⇧m as shortcut

### ISSUE THREAD

**Issue by hytor-yang** [Mortennn/Dozer#91]
Tired different alphabet keys but none works. It seems that either ⌘ or ⌃ has to be involved. Is it by design? If yes would you please clarify the purpose a little bit?

**Comment by gingerbeardman** [comment]
It uses `MASShortcut` framework to do the shortcut key feature.

You can use [ShortcutDetective](http://www.irradiatedsoftware.com/labs/#ShortcutDetective) to find out what app is eating the shortcut and preventing you to use it in Dozer.

**Comment by hytor-yang** [comment]
Thx a lot for the information, gingerbeardman!
Though it did not bother (as I do not use Dozer) anymore, it's certainly great to know ShortcutDetective as a general purpose  tool.
