### ISSUE TITLE
GIF in readme not clear ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by skywinder** [Mortennn/Dozer#92]
On 95% of time I see the basic functionality of mac by moving icons ith cmd pressed. And with 5 times I didn't realize what happens in last miliseconds of gif.

**Comment by jtchristie** [comment]
You move both circles over the icons you want to hide then click one of them to hide all icons to the left of that one.

**Comment by huyz** [comment]
Wow, that was so unintuive!

**Comment by gingerbeardman** [comment]
The readme has usage written in English.

**Comment by huyz** [comment]
Neither the English usage instructions nor the animated GIF explain why there are 2 dot icons.  From a UX standpoint, one would have been sufficient.  Maybe I'm missing something?  If I am, that should be explained in the README.

**Comment by gingerbeardman** [comment]
Yes, I see your point. Both could be a lot better.

** dots (right to left) **
1. position this anywhere, this is your main activator
2. this dot and everything to its left will be hidden/shown by clicking (1)
3. (optional) this dot and everything to its left will be hidden/shown by alt-clicking (1)
