### ISSUE TITLE
Some app icons missing after using Dozer

### ISSUE THREAD

**Issue by shog86** [Mortennn/Dozer#96]
This is my default menu bar
![Screen Shot 2020-02-18 at 10 31 49](https://user-images.githubusercontent.com/19712631/74699283-3bea9980-523b-11ea-880d-ddfd2aa08eb2.jpg)

This is when I open Dozer and make no actions (clickings etc.)
![Screen Shot 2020-02-18 at 10 32 17](https://user-images.githubusercontent.com/19712631/74698883-2628a480-523a-11ea-82ac-ff89c16afc1b.jpg)

And this is when I click the dot and click it again
![Screen Shot 2020-02-18 at 10 34 41](https://user-images.githubusercontent.com/19712631/74698941-4ce6db00-523a-11ea-9927-d03524299b10.jpg)

And to configure iText (the first icon from the left), I need to quit Dozer.

It's been a while, and hope that it can be fixed.

Thanks!

**Comment by shog86** [comment]
I tried to upload images again, but failed...

**Comment by blakedgordon** [comment]
@shog86 that's related to the remove icon. If you option-click one of the icons it will show all your other icons

**Comment by shog86** [comment]
Thank you, @blakedgordon !
