### ISSUE TITLE
hide notification center icon

### ISSUE THREAD

**Issue by shungo27** [Mortennn/Dozer#97]
Please add an option to hide the notification center icon!

**Comment by gingerbeardman** [comment]
Can you post a screenshot?

**Comment by Mortennn** [comment]
The notification center icon is unfortunately not something Dozer can hide. If #69 gets resolved it may be possible.

**Comment by gingerbeardman** [comment]
@shungo27 you can use this: https://github.com/DaFuqtor/barhide
